### PR TITLE
Add WaniKani Colored Dark Themes

### PR DESCRIPTION
**Pull request by Kaiserdragon2**
image
This might also help here #37

### CODE REVIEW

**Comment by Kaiserdragon2** [comment]
Can I ask if this will be implemented into the app or does it need changes to have it be implemented?

**Comment by jerryhcooke** [comment]
Hiya @Kaiserdragon2 

Yes, it will be implemented in the next version - I'm sorry, I'd had some branch messing around in order to get the F-Droid submission validated and so this commit was missed out of the newest build, so I'll be adding it in manually :)

**Comment by Kaiserdragon2** [comment]
I also could make a new pull Request.

**Comment by jerryhcooke** [comment]
Sure thing, that'd be great.

**Pull request merged**
