### PR TITLE
Add monochrome icon

### LINKED ISSUE #35: [Feature Request] Monochrome Icon for Smouldering Durtles
As of Android 12, Android supports monochrome icons on the home screen which are reactive to the user's selected colour scheme (Material You).

I'm on a bit of a mission to get as many of my home page icons to support this functionality as possible and would love to contribute to this project, so if you could provide me with the source document for the icon (png, psd, whatever has the highest quality version) I can contribute the needed patch to add this functionality. 

For example:
Screenshot_20230801-151502

Here, the only app to support themed icons is Kanji Study. It would be great, and a nice little attention to detail effect if Smouldering Durtles also included this 🙂.

As I said, I can provided the change myself, but it would be made easier with access to the original images for the icon.

### PR DESCRIPTION
**Pull request by the-wright-jamie**
Closes #35, this adds a monochrome icon for users of Android 13+ (Material You).

### Dark mode
image

### Light mode
image

### No themed icons
image

### CODE REVIEW

**Comment by the-wright-jamie** [comment]
@jerryhcooke

**Comment by the-wright-jamie** [comment]
ください、Cookeさん。🥺

@jerryhcooke

**Comment by the-wright-jamie** [comment]
おねぎします、Cooke様。🙇‍♂️

@jerryhcooke

**Comment by DropaBombOnEm** [comment]
@the-wright-jamie 

It says "Unable to merge, a review is required", then also says "Reviews: None requested" 😂

(I'm new-ish to GitHub, so I have no idea if that's relevant)

**Comment by the-wright-jamie** [comment]
Welcome to GitHub @DropaBombOnEm! It can be a little confusing if you don't have experience with it, and I appreciate your observation - it certainly does say no reviews are requested. However, I do not have permission to request a review - only 'verified' contributors (i.e. people who have direct commit access), moderators/admins, or owners of the repo can assign reviews to people. 

In a repository I have write access to, you can see that there is a cog that will allow me to add new reviewers:
Screenshot 2023-08-28 at 10 09 17

However, as you might have noticed, this option is lacking in this PR for you as well as for me:
image

This is because, typically, these features are reserved for people who manage the repository so that individuals who are not a part of the project don't abuse the features by spamming tags and requests. 

I have been circumventing that by directly pinging Mr. Cooke, but I feel I have been doing it in a respectful way as he has been absent from the project for over a month. I can see on his profile that he is in university, so he is probably focusing on that work for now which is completely understandable - I know how it is. I'm just hoping that he sees this very small and minor contribution and accepts it, or denies it with a good reason.

Maybe I'm impatient, but I find it a little frustrating when a project is forked and said to be actively developed and then the forker disappears without a word. Again, Mr Cooke, if you're reading this: I understand and this isn't meant to be a slight on you. University comes first, especially considering that it's so expensive. If you are passionate about this project, I would ask you to consider adding a new contributor as a maintainer in your absence so that PRs can be merged and community progress can continue.

I hope, @DropaBombOnEm, this has made sense and I have expanded your knowledge on GitHub and how contributing to open-source projects works - even if it's just by a small fraction.

**Comment by jerryhcooke** [comment]
Hi @the-wright-jamie 

I'm sorry to have not gotten to this previously, when it was a matter of a button click! 🙇🏻‍♂️

I actually work at a university, and in the past month we've had all the students return, and I've had to, for example, develop an entire bookings and payment system from scratch a week before lectures started, so I've been all kinds of stressed, but that's no excuse.

**Comment by the-wright-jamie** [comment]
Nah that's totally understandable, work takes precedence over hobbies. Glad to see you finally got round to be though, thank you 😛

**Pull request merged**
